// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1
// Source: user_rpc.proto

package server

import (
	"context"

	"Easy-GoZero/user/user_rpc/internal/logic"
	"Easy-GoZero/user/user_rpc/internal/svc"
	"Easy-GoZero/user/user_rpc/user_rpc"
)

type UserRpcServer struct {
	svcCtx *svc.ServiceContext
	user_rpc.UnimplementedUserRpcServer
}

func NewUserRpcServer(svcCtx *svc.ServiceContext) *UserRpcServer {
	return &UserRpcServer{
		svcCtx: svcCtx,
	}
}

func (s *UserRpcServer) Ping(ctx context.Context, in *user_rpc.Request) (*user_rpc.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
