// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1

package types

type UserCreateRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type UserInfoRequest struct {
	ID uint `path:"id"`
}

type UserInfoResponse struct {
	UserId   uint   `json:"user_id"`
	Username string `json:"username"`
}
